import { SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { user } = useUser();
  const { data } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!!user && (
          <>
            <h1 className="text-4xl text-white font-bold">
              Welcome, {user?.fullName}!
            </h1>
            <SignOutButton />
          </>
        )}
        <div>
          {data?.map(post => (
            <div key={post.id}>
              <Link href={`/posts/${post.id}`}>
                <h2>{post.content}</h2>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
